spring:
  application:
    name: order-service

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/fingcart_order_db
    username: postgres
    password: <password>
    pool:
      enabled: true
      initial-size: 10
      max-size: 20

  # JDBC configuration (for Flyway migrations)
  datasource:
    url: jdbc:postgresql://localhost:5432/fingcart_order_db
    username: postgres
    password: <password>
    driver-class-name: org.postgresql.Driver

  # Flyway configuration
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    schemas: public

  # Optional: For SQL logging
    logging:
      level:
        org.springframework.r2dbc: DEBUG
        io.r2dbc.postgresql.QUERY: DEBUG  # Log PostgreSQL queries
        io.r2dbc.postgresql.PARAM: DEBUG  # Log query parameters


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

server:
  port:
    9004